# Generated by Django 3.2.8 on 2022-06-16 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(default='Anonymous', max_length=100)),
                ('gender', models.CharField(choices=[('Undentify', 'Undentify'), ('Male', 'Male'), ('Female', 'Female')], default='Undentify', max_length=10)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
