# Generated by Django 3.2.8 on 2022-06-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='change_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Undentify', 'Undentify'), ('Male', 'Male'), ('Female', 'Female')], default='Undentify', max_length=10, verbose_name='Sex'),
        ),
    ]
