# Generated by Django 3.2.8 on 2022-06-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220619_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_posted',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
