# Generated by Django 3.2.8 on 2022-06-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220619_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgerne',
            name='place',
        ),
        migrations.AddField(
            model_name='post',
            name='gerne',
            field=models.ManyToManyField(to='blog.PostGerne'),
        ),
    ]
